file_format: "1"
id: adv360
name: Advantage 360 Pro
type: board
url: https://kinesis-ergo.com/keyboards/advantage360
arch: arm
features:
  - keys
  - underglow
  - backlight
outputs:
  - usb
  - ble
siblings:
  - adv360pro_left
  - adv360pro_right
